spring.application.name=DINERestaurant-Backend

# SQL Server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=dbDINERESTAURANT;encrypt=true;trustServerCertificate=true;
spring.datasource.username=quang123
spring.datasource.password=123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate.format_sql=true

# T?t g?i SMS th?t (ch? in ra console)
twilio.enabled=false

# Các giá tr? Twilio ?? khi b?t l?i v?n dùng ???c (không b?t bu?c lúc này)
twilio.accountSid=dummy_sid
twilio.authToken=dummy_token
twilio.phoneNumber=+1234567890